import { IAIService } from '../../domain/services/IAIService';

export interface GeneratedPromptResult {
  title: string;
  description: string;
  content: string;
}

export class GeneratePrompt {
  constructor(private aiService: IAIService) {}

  async execute(requirement: string, model: string): Promise<GeneratedPromptResult> {
    const systemPrompt = `You are an expert prompt engineer. Your job is to generate a professional, production-ready, and highly-effective prompt template based on the user's requirements.
The prompt template you generate should follow best practices (such as specifying role/persona, clear tasks, formatting constraints, and step-by-step thinking where appropriate).
If the user's description suggests placeholders/variables, use the double brace format (e.g., {{variable_name}}).

CRITICAL REQUIREMENT:
The entire generated prompt template and metadata MUST be written in English.
Exceptions:
- If the user explicitly asks for another language (e.g. "en español", "in Spanish", "in German", etc.), output in that language instead.
- If the user's prompt requirement is specifically about translating to/from a language, output in the requested target language.

Format your output exactly as follows with the dividers. Do not include any other markdown decoration outside these blocks:
===TITLE===
[A concise, creative 3-5 word title]
===DESCRIPTION===
[A brief one-sentence description of what this prompt does]
===PROMPT===
[The complete, direct, and detailed prompt template, including placeholders like {{placeholder}} if needed]`;

    try {
      const response = await this.aiService.generate(requirement, model, systemPrompt);
      
      let title = 'Generated Prompt';
      let description = 'Generated by AI based on requirements';
      let content = '';

      if (response.includes('===TITLE===') && response.includes('===DESCRIPTION===') && response.includes('===PROMPT===')) {
        const titlePart = response.split('===TITLE===')[1].split('===DESCRIPTION===')[0].trim();
        const descPart = response.split('===DESCRIPTION===')[1].split('===PROMPT===')[0].trim();
        const promptPart = response.split('===PROMPT===')[1].trim();
        
        title = titlePart;
        description = descPart;
        content = promptPart;
      } else {
        // Fallback parsing if formatting fails
        content = response;
      }

      return {
        title,
        description,
        content
      };
    } catch (error) {
      console.error('Failed to generate prompt from AI:', error);
      throw error;
    }
  }
}
